### ISSUE TITLE
Errors building

### ISSUE THREAD

**Issue by danipolo** [tom472/mediabox#14]
Hi, I'm trying to deploy this awesome stack and getting the following errors while installing:

```
...............
Creating watchtower
Creating plexpy
./mediabox.sh: line 113: latest:: command not found


CouchPotato requires access to the Deluge daemon port and needs credentials set.
What would you like to use as the daemon access username?: admin
What would you like to use as the daemon access password?: -------


Configuring Deluge daemon access - UHTTPD index file - Permissions 

sed: can't read delugevpn/config/core.conf: No such file or directory
sed: can't read delugevpn/config/core.conf: No such file or directory
sed: can't read delugevpn/config/core.conf: No such file or directory
sed: can't read delugevpn/config/core.conf: No such file or directory
```

Ubuntu 16 Xenial fresh install.

**Comment by tom472** [comment]
This line:
`./mediabox.sh: line 113: latest:: command not found`
Has been something there for a bit - I am no longer pulling any images with the "latest" tag anymore - but even it not specified - "latest" is assumed by default. We'll see if this corrects it.

As for the issues with the sed commands - I just started seeing this too.
Looks like there is an issue with this part running if the DelugeVPN container has not fully come up yet.
Working on some fixes for this right now.

Sorry about that -- 
Stay tuned - hopefully won't take too long.

**Comment by tom472** [comment]
OK try giving this another shot.
Issues should be corrected now.

Let me know how it goes.

**Comment by tom472** [comment]
Any chance to get back to trying this again? 

Thanks

**Comment by tom472** [comment]
No word back from @danipolo - however through some other testing it looks like the issue has been resolved.

**Comment by danipolo** [comment]
Sorry @tom472 didn't see. I will check again. Thanks

**Comment by tom472** [comment]
@danipolo  Was it better now?

**Comment by danipolo** [comment]
Sure but I still having issues with DelugeVPN. I will detail it soon with
more info. Thanks.
